permalink: /:year/:title:output_ext

future: true

include: [_redirects, .htcaccess]

collections:
  matches:
    output: false
  servers:
    output: false
  teams:
    output: true
    permalink: /:collection/:name
  partners:
    output: false
  players:
    output: true
  tournaments:
    output: true
    permalink: /:collection/:year/:month/:title

title: Quixz eSports
email: contact@quixz.eu
description: >- # this means to ignore newlines until "baseurl:"
  The homepage for esports organization Quixz eSports
baseurl:  # the subpath of your site, e.g. /blog
url: "https://quixz.eu" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-sitemap


defaults:
  -
    scope:
      path:            "admin"
    values:
      sitemap:         false
