permalink: /:categories/:year/:title:output_ext

future: true

include: [_redirects]

collections:
  - matches

permalink: pretty

title: Quixz eSports
email: contact@quixz.eu
description: >- # this means to ignore newlines until "baseurl:"
  The homepage for esports organization Quixz eSports
baseurl:  # the subpath of your site, e.g. /blog
url: "https://quixz.eu" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-compress-images

defaults:
  -
    scope:
      path:            "admin"
    values:
      sitemap:         false


compress_images:
  images_path: "assets/image/**/*.{gif,png,jpg,jpeg,svg}"
