backend:
  name: git-gateway
  repo: Barsnes/Quixz_eSports

editor:
   preview: false

display_url: https://quixz.eu

media_folder: "/assets/image/articles" # Media files will be stored in the repo under images/uploads

media_library:
  name: uploadcare
  config:
    publicKey: dcd4677d02e4ff379685
    multiple: true

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "article" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Article" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    layout: "article.html"
    sort: "date:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "default_blog"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date", format: "DD-MM-YYYY"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown", tagname: "p"}
      - {label: "categories", name: "categories", widget: "hidden", default: "news"}
      - label: "Featured Image"
        name: "Image"
        widget: "image"
        options:
          media_library:
            config:
              publicKey: dcd4677d02e4ff379685
              multiple: true
              
  - name: "macthes" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Upcoming Matches" # Used in the UI, ie.: "New Post"
    delete: true
    create: true
    slug: "{{matchdate}}-{{slug}}"
    folder: "_matches"
    fields: # The fields each document in this collection have
          - {label: "Match", name: "title", widget: "string", default:""}
          - {label: "Date", name: "matchdate", widget: "date", format: "YYYY-MM-DD"}
          - {label: "Game", name: "game", widget: "select", options: ["Counter Strike", "Rocket League", "League of Legends", "Hearthstone"]}
          - {label: "Link", name: "matchlink", widget: "string", required: false}
          - label: "Team logo"
            name: "image"
            widget: "image"
            defualt: "default_team_logo.png"

  - name: "player"
    label: "Player"
    delete: true
    create: true
    slug: "{{playername}}-{{slug}}"
    folder: "_posts/player"
    fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "players"}
          - {label: "Title", name: "title", widget: "hidden", default: "Player"}
          - {label: "First Name", name: "firstname", widget: "string"}
          - {label: "Nickname", name: "playername", widget: "string"}
          - {label: "Last name", name: "lastname", widget: "string"}
          - label: "Photo"
            name: "playerimage"
            widget: "image"
            defualt: "/assets/image/articles/avatar.png"
            options:
              media_library:
                config:
          - {label: "Game", name: "playergame", widget: "select", options: ["Counter Strike", "Rocket League", "League of Legends", "Hearthstone"]}
          - {label: "Text", name: "body", widget: "markdown", tagname: "p", required: false}
          - {label: "Gallery", name: "gallery", widget: "markdown", default: "We currently do not have any pictures", required: false}
          - {label: "Twitter", name: "twitter", widget: "string", required: false}
          - {label: "Twitch", name: "twitch", widget: "string", required: false}
          - {label: "Youtube", name: "youtube", widget: "string", required: false}
          - {label: "Steam", name: "steam", widget: "string", required: false}
          - {label: "Instagram", name: "instagram", widget: "string", required: false}
          - {label: "categories", name: "categories", widget: "hidden", default: "player"}
          - {label: "permalink", name: "permalink", widget: "hidden", default: "permalink: /player/:slug"}
          
          

  - name: "server"
    label: "Servers"
    delete: true
    create: true
    slug: "{{servername}}-{{slug}}"
    folder: "_servers"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Server Info", name: "server", widget: "string"}

  - name: "about" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Pages" # Used in the UI, ie.: "New Post"
    delete: false
    files: # The path to the folder where the documents are stored
      - label: "About"
        name: "about"
        slug: "about"
        file: "about.md"
        delete: false
        fields: # The fields each document in this collection have
          - {label: "Title", name: "title", widget: "hidden", default: "About"}
          - {label: "Title", name: "title_about", default: "Our History"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
          - {label: "Body", name: "body", widget: "markdown", tagname: "p"}
