backend:
  name: git-gateway
  repo: Barsnes/Quixz_eSports
  accept_roles:
    - admin
  base_url: https://api.netlify.com

editor:
   preview: false

display_url: https://quixz.eu

media_folder: "/assets/image/articles"

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "article"
    label: "Article"
    folder: "_posts"
    layout: "article.html"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default_blog"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date", format: "DD-MM-YYYY"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown", tagname: "p"}
      - {label: "categories", name: "categories", widget: "string", default: "news, csgo, ow, rl, hs"}
      - label: "Featured Image"
        name: "image"
        widget: "image"

  - name: "matches"
    label: "Upcoming Matches"
    delete: true
    create: true
    slug: "{{matchdate}}-{{slug}}"
    folder: "_matches"
    fields:
          - {label: "Match", name: "title", widget: "string", default:""}
          - {label: "Date", name: "matchdate", widget: "date", format: "YYYY-MM-DD"}
          - {label: "Game", name: "game", widget: "select", options: ["Counter Strike", "Rocket League", "League of Legends", "Hearthstone", "Overwatch"]}
          - {label: "Link", name: "matchlink", widget: "string", required: false}
          - label: "Team logo"
            name: "image"
            widget: "image"
            defualt: "default_team_logo.png"
          - label: "Score"
            name: "score"
            widget: "object"
            fields:
              - {label: "Quixz", name: "quixzScore", widget: "string", default:"0"}
              - {label: "Opponent", name: "opponentScore", widget: "string", default:"0"}

  - name: "player"
    label: "Player"
    delete: true
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{playername}}-{{slug}}"
    folder: "_players"
    fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "players"}
          - {label: "Playername", name: "title", widget: "string"}
          - {label: "Active", name: "status", widget: "select", options: ["true", "false"]}
          - label: "Name"
            name: "name"
            widget: "object"
            fields:
              - {label: "First Name", name: "firstname", widget: "string"}
              - {label: "Nickname", name: "playername", widget: "string"}
              - {label: "Last name", name: "lastname", widget: "string"}
          - label: "Photo"
            name: "playerimage"
            widget: "image"
            defualt: "/assets/image/articles/avatar.png"
          - {label: "Game", name: "playergame", widget: "select", options: ["Counter Strike", "Rocket League", "League of Legends", "Hearthstone"]}
          - {label: "Text", name: "body", widget: "markdown", tagname: "p", required: false}
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            field: {label: "Gallery Image", name: "galleryImage", widget: image}
          - label: "Social Media"
            name: "sm"
            widget: "object"
            required: false
            fields:
              - {label: "Twitter", name: "twitter", widget: "string", required: false}
              - {label: "Twitch", name: "twitch", widget: "string", required: false}
              - {label: "Youtube", name: "youtube", widget: "string", required: false}
              - {label: "Steam", name: "steam", widget: "string", required: false}
              - {label: "Instagram", name: "instagram", widget: "string", required: false}
          - {label: "categories", name: "categories", widget: "hidden", default: "player"}
          - {label: "permalink", name: "permalink", widget: "hidden", default: "permalink: /player/:slug"}

  - name: "server"
    label: "Servers"
    delete: true
    create: true
    slug: "{{servername}}-{{slug}}"
    folder: "_servers"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Server Info", name: "server", widget: "string"}

  - name: "teams"
    label: "Team Pages"
    delete: false
    create: false
    slug: "{{teamgame}}-{{slug}}"
    folder: "_teams"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "teampage"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Game", name: "game", widget: "select", options: ["Counter Strike", "Rocket League", "League of Legends", "Hearthstone", "Overwatch"]}
      - {label: "About", name: "body", widget: "markdown"}
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        field: {label: Image, name: image, widget: image}
      - label: "Page Design"
        name: "pageDesign"
        widget: "object"
        fields:
          - {label: "Background Image", name: "bgImage", widget: "image"}
      - label: "Win / Loss"
        name: "ratio"
        widget: "object"
        required: false
        fields:
          - {label: "Wins", name: "win", widget: "string"}
          - {label: "Loss", name: "loss", widget: "string"}

  - name: "pages"
    label: "Pages"
    delete: false
    files:
      - label: "Homepage"
        name: "index"
        slug: "index"
        file: "index.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "hidden", default: "Home"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "index"}
          - {label: "Description", name: "description", widget: "markdown", default: "Quixz eSports is an organization, founded in 2015. We represent teams in several esport titles, such as CSGO and Rocket League. Our passions for the esport community is strong, and try our best to make it grow better!"}
          - {label: "About", name: "about", widget: "markdown"}
      - label: "About"
        name: "about"
        slug: "about"
        file: "about.md"
        delete: false
        fields:
          - {label: "Title", name: "title", widget: "hidden", default: "About"}
          - {label: "Title", name: "title_about", default: "Our History"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
          - {label: "Body", name: "body", widget: "markdown", tagname: "p"}

  - name: "partner"
    label: "Partners"
    delete: true
    create: true
    slug: "{{title}}-{{slug}}"
    folder: "_partners"
    fields:
      - {label: "Partner", name: "title", widget: "string"}
      - {label: "Active", name: "status", widget: "select", options: ["true", "false"]}
      - {label: "Website", name: "website", widget: "string"}
      - {label: "Logo", name: "image", widget: "image"}
