backend:
  name: git-gateway
  repo: Barsnes/Quixz_eSports
  accept_roles: #optional - accepts all users if left out
    - admin

editor:
   preview: false

display_url: https://quixz.eu

media_folder: "/assets/image/articles" # Media files will be stored in the repo under images/uploads

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "article" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Article" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    layout: "article.html"
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{date}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "default_blog"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Image", name: "image", widget: "image", tagname: "img"}
      - {label: "Publish Date", name: "date", widget: "date", format: "DD-MM-YYYY"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown", tagname: "p"}
      - {label: "Description", name: "description", widget: "string", default: "Only vivible on the Articles page"}

  - name: "macthes" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Upcoming Matches" # Used in the UI, ie.: "New Post"
    delete: true
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    folder: "_matches"
    fields: # The fields each document in this collection have
          - {label: "Match", name: "title", widget: "string", default:""}
          - {label: "Team Logo", name: "image", widget: "image", defualt: "assets/image/articles/default_team_logo.png"}
          - {label: "Date", name: "matchdate", widget: "date", format: "DD-MM-YYYY"}
          - {label: "Game", name: "game", widget: "select", options: ["Counter Strike", "Rocket League", "League of Legends", "Hearthstone"]}
          - {label: "Link", name: "matchlink", widget: "string"}

  - name: "about" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "About" # Used in the UI, ie.: "New Post"
    delete: false
    files: # The path to the folder where the documents are stored
      - label: "About"
        name: "about"
        slug: "about"
        file: "about.md"
        delete: false
        fields: # The fields each document in this collection have
          - {label: "Title", name: "title", widget: "hidden", default: "About"}
          - {label: "Title", name: "title_about", default: "Our History"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "about"}
          - {label: "Body", name: "body", widget: "markdown", tagname: "p"}
