backend:
  name: github
  repo: Barsnes/Quixz_eSports # your GitHub username and repository name, separated by a slash
  branch: master # optional, default value is "master"

media_folder: "../assets" # Media files will be stored in the repo under images/uploads
publish_mode: editorial_workflow


collections:
  label: "Blog"
  name: "blog"
  folder: "_posts/blog"
  create: true
  fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Featured Image", name: "thumbnail", widget: "image"}
    - {label: "Body", name: "body", widget: "markdown"}
